

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: devalchemytest
      MYSQL_USER: devalchemy
      MYSQL_PASSWORD: devalchemy
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  mynetwork:

volumes:
  mysql_data: